name: Taipy
channels:
  - defaults
dependencies:
  - pip
  - python=3.12.11
  - pip:
      - numpy==2.3.3
      - openpyxl==3.1.2
      - pandas==2.2.2
      - scipy==1.16.2
      - sympy==1.14.0
      - taipy==4.1.0
prefix: /opt/conda/envs/Taipy
