[project]
name = "kurzschlussfestigkeit"
version = "0.0.1-dev"
description = "Auslegung der Kurzschlussfestigkeit von Betriebsmitteln"
authors = [{name = "Kalandoros", email = "info@uwcalc.ch"}]
readme = "README.md"
requires-python = ">=3.11"
keywords = ["electrical-engineering", "short-circuit", "taipy", "engineering-calc"]
dependencies = [
    "numpy==2.3.3",
    "openpyxl==3.1.2",
    "pandas==2.2.2",
    "scipy==1.16.2",
    "sympy==1.14.0",
    "taipy==4.1.0",
]

[project.urls]
Homepage = "https://uwcalc.ch/"
Repository = "https://github.com/Kalandoros/Kurzschlussfestigkeit"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.xlsx", "*.json", "*.css"]